[2023-03-02T21:12:44.107+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T21:12:39.655406+00:00 [queued]>
[2023-03-02T21:12:44.131+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T21:12:39.655406+00:00 [queued]>
[2023-03-02T21:12:44.133+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T21:12:44.133+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T21:12:44.133+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T21:12:44.183+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): main> on 2023-03-02 21:12:39.655406+00:00
[2023-03-02T21:12:44.206+0000] {standard_task_runner.py:55} INFO - Started process 681 to run task
[2023-03-02T21:12:44.234+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'convert_csv_in_excel', 'main', 'manual__2023-03-02T21:12:39.655406+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/convert_csv_in_excel.py', '--cfg-path', '/tmp/tmpi6ws71kv']
[2023-03-02T21:12:44.242+0000] {standard_task_runner.py:83} INFO - Job 116: Subtask main
[2023-03-02T21:12:44.452+0000] {task_command.py:388} INFO - Running <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T21:12:39.655406+00:00 [running]> on host d28bc369eb67
[2023-03-02T21:12:44.616+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=convert_csv_in_excel
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T21:12:39.655406+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-02T21:12:39.655406+00:00
[2023-03-02T21:12:46.060+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192: DtypeWarning: Columns (7,8,11,13,31,43,44) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2023-03-02T21:12:46.153+0000] {python.py:177} INFO - Done. Returned value was:         Mission ID Mission Date  ... Bomb Damage Assessment Source ID
0                1    8/15/1943  ...                    NaN       NaN
1                2    8/15/1943  ...                    NaN    9366.0
2                3    8/15/1943  ...                    NaN       NaN
3                4    8/15/1943  ...                    NaN       NaN
4                5    8/15/1943  ...                    NaN   22585.0
...            ...          ...  ...                    ...       ...
178276      178738    2/16/1945  ...                    NaN   35815.0
178277      178739    2/16/1945  ...                    NaN   35020.0
178278      178740    2/16/1945  ...                    NaN   35022.0
178279      178741    2/16/1945  ...                    NaN       NaN
178280      178742    2/16/1945  ...                    NaN   33784.0

[178281 rows x 46 columns]
[2023-03-02T21:12:46.305+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-03-02T21:12:46.307+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-03-02T21:12:46.329+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=convert_csv_in_excel, task_id=main, execution_date=20230302T211239, start_date=20230302T211244, end_date=20230302T211246
[2023-03-02T21:12:46.365+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 116 for task main (Object of type DataFrame is not JSON serializable; 681)
[2023-03-02T21:12:46.419+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T21:12:46.486+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
